#ifndef OCLingCoreConnect_h
#define OCLingCoreConnect_h

/**
 * 关键字方式
 */
#if DEBUG
#define OCLING_CORNECT_KEYWORD_DEF                 autoreleasepool {}
#define OCLING_CORNECT_KEYWORD_DEF_INNER(...)      autoreleasepool {__VA_ARGS__}
#else
#define OCLING_CORNECT_KEYWORD_DEF                 try {} @catch (...) {}
#endif

#define OCLING_CORNECT_CONCAT_(A, B) A ## B
/// 拼接宏
#define OCLING_CORNECT_CONCAT(A, B) \
OCLING_CORNECT_CONCAT_(A, B)
/// 索引取参数 N总数
#define OCLING_CORNECT_AT(N, ...) \
OCLING_CORNECT_CONCAT(OCLING_CORNECT_AT, N)(__VA_ARGS__)
/// 参数数目，最少返回一个
#define OCLING_CORNECT_ARGCOUNT(...) \
OCLING_CORNECT_AT(20, __VA_ARGS__, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1)
///
#define OCLING_CORNECT_FOREACH(MACRO, SEP, ...) \
OCLING_CORNECT_FOREACH_CXT(OCLING_CORNECT_FOREACH_ITER, SEP, MACRO, __VA_ARGS__)
/// MACRO(索引,分隔符,内容,参数)
#define OCLING_CORNECT_FOREACH_CXT(MACRO, SEP, CONTEXT, ...) \
OCLING_CORNECT_CONCAT(OCLING_CORNECT_FOREACH_CXT, OCLING_CORNECT_ARGCOUNT(__VA_ARGS__))(MACRO, SEP, CONTEXT, __VA_ARGS__)
/// 数字相等(执行是)(执行否)
#define OCLING_CORNECT_IF_EQ(A, B) \
OCLING_CORNECT_CONCAT(OCLING_CORNECT_IF_EQ, A)(B)

#define OCLING_CORNECT_HEAD_(FIRST, ...) FIRST
#define OCLING_CORNECT_TAIL_(FIRST, ...) __VA_ARGS__
/// 第一个参数
#define OCLING_CORNECT_HEAD(...) OCLING_CORNECT_HEAD_(__VA_ARGS__, 0)
/// 除了第一个参数
#define OCLING_CORNECT_TAIL(...) OCLING_CORNECT_TAIL_(__VA_ARGS__)

#define OCLING_CORNECT_DEC(VAL) \
OCLING_CORNECT_AT(VAL, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19)

#define OCLING_CORNECT_CONSUME_(...)

#define OCLING_CORNECT_EXPAND_(...) __VA_ARGS__
/// 连接；SEP,args...
#define OCLING_CORNECT_JOIN_WITH(SEP,...) OCLING_CORNECT_CONCAT(OCLING_CORNECT_JOIN_WITH,OCLING_CORNECT_ARGCOUNT(__VA_ARGS__))(SEP,__VA_ARGS__)
//AADD_OCLING_CORNECT_JOIN_WITH1
// OCLING_CORNECT_AT expansions
#define OCLING_CORNECT_AT0(...) OCLING_CORNECT_HEAD(__VA_ARGS__)
#define OCLING_CORNECT_AT1(_0, ...) OCLING_CORNECT_HEAD(__VA_ARGS__)
#define OCLING_CORNECT_AT2(_0, _1, ...) OCLING_CORNECT_HEAD(__VA_ARGS__)
#define OCLING_CORNECT_AT3(_0, _1, _2, ...) OCLING_CORNECT_HEAD(__VA_ARGS__)
#define OCLING_CORNECT_AT4(_0, _1, _2, _3, ...) OCLING_CORNECT_HEAD(__VA_ARGS__)
#define OCLING_CORNECT_AT5(_0, _1, _2, _3, _4, ...) OCLING_CORNECT_HEAD(__VA_ARGS__)
#define OCLING_CORNECT_AT6(_0, _1, _2, _3, _4, _5, ...) OCLING_CORNECT_HEAD(__VA_ARGS__)
#define OCLING_CORNECT_AT7(_0, _1, _2, _3, _4, _5, _6, ...) OCLING_CORNECT_HEAD(__VA_ARGS__)
#define OCLING_CORNECT_AT8(_0, _1, _2, _3, _4, _5, _6, _7, ...) OCLING_CORNECT_HEAD(__VA_ARGS__)
#define OCLING_CORNECT_AT9(_0, _1, _2, _3, _4, _5, _6, _7, _8, ...) OCLING_CORNECT_HEAD(__VA_ARGS__)
#define OCLING_CORNECT_AT10(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, ...) OCLING_CORNECT_HEAD(__VA_ARGS__)
#define OCLING_CORNECT_AT11(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, ...) OCLING_CORNECT_HEAD(__VA_ARGS__)
#define OCLING_CORNECT_AT12(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, ...) OCLING_CORNECT_HEAD(__VA_ARGS__)
#define OCLING_CORNECT_AT13(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, ...) OCLING_CORNECT_HEAD(__VA_ARGS__)
#define OCLING_CORNECT_AT14(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, ...) OCLING_CORNECT_HEAD(__VA_ARGS__)
#define OCLING_CORNECT_AT15(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, ...) OCLING_CORNECT_HEAD(__VA_ARGS__)
#define OCLING_CORNECT_AT16(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, ...) OCLING_CORNECT_HEAD(__VA_ARGS__)
#define OCLING_CORNECT_AT17(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, ...) OCLING_CORNECT_HEAD(__VA_ARGS__)
#define OCLING_CORNECT_AT18(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, ...) OCLING_CORNECT_HEAD(__VA_ARGS__)
#define OCLING_CORNECT_AT19(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, ...) OCLING_CORNECT_HEAD(__VA_ARGS__)
#define OCLING_CORNECT_AT20(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, ...) OCLING_CORNECT_HEAD(__VA_ARGS__)


#define OCLING_CORNECT_IF_EQ0(VALUE) \
OCLING_CORNECT_CONCAT(OCLING_CORNECT_IF_EQ0_, VALUE)

#define OCLING_CORNECT_IF_EQ0_0(...) __VA_ARGS__ OCLING_CORNECT_CONSUME_
#define OCLING_CORNECT_IF_EQ0_1(...) OCLING_CORNECT_EXPAND_
#define OCLING_CORNECT_IF_EQ0_2(...) OCLING_CORNECT_EXPAND_
#define OCLING_CORNECT_IF_EQ0_3(...) OCLING_CORNECT_EXPAND_
#define OCLING_CORNECT_IF_EQ0_4(...) OCLING_CORNECT_EXPAND_
#define OCLING_CORNECT_IF_EQ0_5(...) OCLING_CORNECT_EXPAND_
#define OCLING_CORNECT_IF_EQ0_6(...) OCLING_CORNECT_EXPAND_
#define OCLING_CORNECT_IF_EQ0_7(...) OCLING_CORNECT_EXPAND_
#define OCLING_CORNECT_IF_EQ0_8(...) OCLING_CORNECT_EXPAND_
#define OCLING_CORNECT_IF_EQ0_9(...) OCLING_CORNECT_EXPAND_
#define OCLING_CORNECT_IF_EQ0_10(...) OCLING_CORNECT_EXPAND_
#define OCLING_CORNECT_IF_EQ0_11(...) OCLING_CORNECT_EXPAND_
#define OCLING_CORNECT_IF_EQ0_12(...) OCLING_CORNECT_EXPAND_
#define OCLING_CORNECT_IF_EQ0_13(...) OCLING_CORNECT_EXPAND_
#define OCLING_CORNECT_IF_EQ0_14(...) OCLING_CORNECT_EXPAND_
#define OCLING_CORNECT_IF_EQ0_15(...) OCLING_CORNECT_EXPAND_
#define OCLING_CORNECT_IF_EQ0_16(...) OCLING_CORNECT_EXPAND_
#define OCLING_CORNECT_IF_EQ0_17(...) OCLING_CORNECT_EXPAND_
#define OCLING_CORNECT_IF_EQ0_18(...) OCLING_CORNECT_EXPAND_
#define OCLING_CORNECT_IF_EQ0_19(...) OCLING_CORNECT_EXPAND_
#define OCLING_CORNECT_IF_EQ0_20(...) OCLING_CORNECT_EXPAND_

#define OCLING_CORNECT_IF_EQ1(VALUE) OCLING_CORNECT_IF_EQ0(OCLING_CORNECT_DEC(VALUE))
#define OCLING_CORNECT_IF_EQ2(VALUE) OCLING_CORNECT_IF_EQ1(OCLING_CORNECT_DEC(VALUE))
#define OCLING_CORNECT_IF_EQ3(VALUE) OCLING_CORNECT_IF_EQ2(OCLING_CORNECT_DEC(VALUE))
#define OCLING_CORNECT_IF_EQ4(VALUE) OCLING_CORNECT_IF_EQ3(OCLING_CORNECT_DEC(VALUE))
#define OCLING_CORNECT_IF_EQ5(VALUE) OCLING_CORNECT_IF_EQ4(OCLING_CORNECT_DEC(VALUE))
#define OCLING_CORNECT_IF_EQ6(VALUE) OCLING_CORNECT_IF_EQ5(OCLING_CORNECT_DEC(VALUE))
#define OCLING_CORNECT_IF_EQ7(VALUE) OCLING_CORNECT_IF_EQ6(OCLING_CORNECT_DEC(VALUE))
#define OCLING_CORNECT_IF_EQ8(VALUE) OCLING_CORNECT_IF_EQ7(OCLING_CORNECT_DEC(VALUE))
#define OCLING_CORNECT_IF_EQ9(VALUE) OCLING_CORNECT_IF_EQ8(OCLING_CORNECT_DEC(VALUE))
#define OCLING_CORNECT_IF_EQ10(VALUE) OCLING_CORNECT_IF_EQ9(OCLING_CORNECT_DEC(VALUE))
#define OCLING_CORNECT_IF_EQ11(VALUE) OCLING_CORNECT_IF_EQ10(OCLING_CORNECT_DEC(VALUE))
#define OCLING_CORNECT_IF_EQ12(VALUE) OCLING_CORNECT_IF_EQ11(OCLING_CORNECT_DEC(VALUE))
#define OCLING_CORNECT_IF_EQ13(VALUE) OCLING_CORNECT_IF_EQ12(OCLING_CORNECT_DEC(VALUE))
#define OCLING_CORNECT_IF_EQ14(VALUE) OCLING_CORNECT_IF_EQ13(OCLING_CORNECT_DEC(VALUE))
#define OCLING_CORNECT_IF_EQ15(VALUE) OCLING_CORNECT_IF_EQ14(OCLING_CORNECT_DEC(VALUE))
#define OCLING_CORNECT_IF_EQ16(VALUE) OCLING_CORNECT_IF_EQ15(OCLING_CORNECT_DEC(VALUE))
#define OCLING_CORNECT_IF_EQ17(VALUE) OCLING_CORNECT_IF_EQ16(OCLING_CORNECT_DEC(VALUE))
#define OCLING_CORNECT_IF_EQ18(VALUE) OCLING_CORNECT_IF_EQ17(OCLING_CORNECT_DEC(VALUE))
#define OCLING_CORNECT_IF_EQ19(VALUE) OCLING_CORNECT_IF_EQ18(OCLING_CORNECT_DEC(VALUE))
#define OCLING_CORNECT_IF_EQ20(VALUE) OCLING_CORNECT_IF_EQ19(OCLING_CORNECT_DEC(VALUE))

#define OCLING_CORNECT_FOREACH_ITER(INDEX, MACRO, ARG) MACRO(INDEX, ARG)

#pragma mark - FOREACH CXT
#define OCLING_CORNECT_FOREACH_CXT0(MACRO, SEP, CONTEXT)
#define OCLING_CORNECT_FOREACH_CXT1(MACRO, SEP, CONTEXT, _0) MACRO(0, CONTEXT, _0)

#define OCLING_CORNECT_FOREACH_CXT2(MACRO, SEP, CONTEXT, _0, _1) \
    OCLING_CORNECT_FOREACH_CXT1(MACRO, SEP, CONTEXT, _0) \
    SEP \
    MACRO(1, CONTEXT, _1)

#define OCLING_CORNECT_FOREACH_CXT3(MACRO, SEP, CONTEXT, _0, _1, _2) \
    OCLING_CORNECT_FOREACH_CXT2(MACRO, SEP, CONTEXT, _0, _1) \
    SEP \
    MACRO(2, CONTEXT, _2)

#define OCLING_CORNECT_FOREACH_CXT4(MACRO, SEP, CONTEXT, _0, _1, _2, _3) \
    OCLING_CORNECT_FOREACH_CXT3(MACRO, SEP, CONTEXT, _0, _1, _2) \
    SEP \
    MACRO(3, CONTEXT, _3)

#define OCLING_CORNECT_FOREACH_CXT5(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4) \
    OCLING_CORNECT_FOREACH_CXT4(MACRO, SEP, CONTEXT, _0, _1, _2, _3) \
    SEP \
    MACRO(4, CONTEXT, _4)

#define OCLING_CORNECT_FOREACH_CXT6(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5) \
    OCLING_CORNECT_FOREACH_CXT5(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4) \
    SEP \
    MACRO(5, CONTEXT, _5)

#define OCLING_CORNECT_FOREACH_CXT7(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6) \
    OCLING_CORNECT_FOREACH_CXT6(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5) \
    SEP \
    MACRO(6, CONTEXT, _6)

#define OCLING_CORNECT_FOREACH_CXT8(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7) \
    OCLING_CORNECT_FOREACH_CXT7(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6) \
    SEP \
    MACRO(7, CONTEXT, _7)

#define OCLING_CORNECT_FOREACH_CXT9(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7, _8) \
    OCLING_CORNECT_FOREACH_CXT8(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7) \
    SEP \
    MACRO(8, CONTEXT, _8)

#define OCLING_CORNECT_FOREACH_CXT10(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9) \
    OCLING_CORNECT_FOREACH_CXT9(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7, _8) \
    SEP \
    MACRO(9, CONTEXT, _9)

#define OCLING_CORNECT_FOREACH_CXT11(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10) \
    OCLING_CORNECT_FOREACH_CXT10(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9) \
    SEP \
    MACRO(10, CONTEXT, _10)

#define OCLING_CORNECT_FOREACH_CXT12(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11) \
    OCLING_CORNECT_FOREACH_CXT11(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10) \
    SEP \
    MACRO(11, CONTEXT, _11)

#define OCLING_CORNECT_FOREACH_CXT13(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12) \
    OCLING_CORNECT_FOREACH_CXT12(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11) \
    SEP \
    MACRO(12, CONTEXT, _12)

#define OCLING_CORNECT_FOREACH_CXT14(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13) \
    OCLING_CORNECT_FOREACH_CXT13(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12) \
    SEP \
    MACRO(13, CONTEXT, _13)

#define OCLING_CORNECT_FOREACH_CXT15(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14) \
    OCLING_CORNECT_FOREACH_CXT14(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13) \
    SEP \
    MACRO(14, CONTEXT, _14)

#define OCLING_CORNECT_FOREACH_CXT16(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15) \
    OCLING_CORNECT_FOREACH_CXT15(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14) \
    SEP \
    MACRO(15, CONTEXT, _15)

#define OCLING_CORNECT_FOREACH_CXT17(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16) \
    OCLING_CORNECT_FOREACH_CXT16(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15) \
    SEP \
    MACRO(16, CONTEXT, _16)

#define OCLING_CORNECT_FOREACH_CXT18(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17) \
    OCLING_CORNECT_FOREACH_CXT17(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16) \
    SEP \
    MACRO(17, CONTEXT, _17)

#define OCLING_CORNECT_FOREACH_CXT19(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18) \
    OCLING_CORNECT_FOREACH_CXT18(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17) \
    SEP \
    MACRO(18, CONTEXT, _18)

#define OCLING_CORNECT_FOREACH_CXT20(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19) \
    OCLING_CORNECT_FOREACH_CXT19(MACRO, SEP, CONTEXT, _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18) \
    SEP \
    MACRO(19, CONTEXT, _19)


#define OCLING_CORNECT_JOIN_WITH1(SEP,head)      head
#define OCLING_CORNECT_JOIN_WITH2(SEP,head,...)  OCLING_CORNECT_CONCAT(OCLING_CORNECT_CONCAT(head,SEP),OCLING_CORNECT_JOIN_WITH1(SEP,__VA_ARGS__))
#define OCLING_CORNECT_JOIN_WITH3(SEP,head,...)  OCLING_CORNECT_CONCAT(OCLING_CORNECT_CONCAT(head,SEP),OCLING_CORNECT_JOIN_WITH2(SEP,__VA_ARGS__))
#define OCLING_CORNECT_JOIN_WITH4(SEP,head,...)  OCLING_CORNECT_CONCAT(OCLING_CORNECT_CONCAT(head,SEP),OCLING_CORNECT_JOIN_WITH3(SEP,__VA_ARGS__))
#define OCLING_CORNECT_JOIN_WITH5(SEP,head,...)  OCLING_CORNECT_CONCAT(OCLING_CORNECT_CONCAT(head,SEP),OCLING_CORNECT_JOIN_WITH4(SEP,__VA_ARGS__))
#define OCLING_CORNECT_JOIN_WITH6(SEP,head,...)  OCLING_CORNECT_CONCAT(OCLING_CORNECT_CONCAT(head,SEP),OCLING_CORNECT_JOIN_WITH5(SEP,__VA_ARGS__))
#define OCLING_CORNECT_JOIN_WITH7(SEP,head,...)  OCLING_CORNECT_CONCAT(OCLING_CORNECT_CONCAT(head,SEP),OCLING_CORNECT_JOIN_WITH6(SEP,__VA_ARGS__))
#define OCLING_CORNECT_JOIN_WITH8(SEP,head,...)  OCLING_CORNECT_CONCAT(OCLING_CORNECT_CONCAT(head,SEP),OCLING_CORNECT_JOIN_WITH7(SEP,__VA_ARGS__))
#define OCLING_CORNECT_JOIN_WITH9(SEP,head,...)  OCLING_CORNECT_CONCAT(OCLING_CORNECT_CONCAT(head,SEP),OCLING_CORNECT_JOIN_WITH8(SEP,__VA_ARGS__))
#define OCLING_CORNECT_JOIN_WITH10(SEP,head,...) OCLING_CORNECT_CONCAT(OCLING_CORNECT_CONCAT(head,SEP),OCLING_CORNECT_JOIN_WITH9(SEP,__VA_ARGS__))
#define OCLING_CORNECT_JOIN_WITH11(SEP,head,...) OCLING_CORNECT_CONCAT(OCLING_CORNECT_CONCAT(head,SEP),OCLING_CORNECT_JOIN_WITH10(SEP,__VA_ARGS__))
#define OCLING_CORNECT_JOIN_WITH12(SEP,head,...) OCLING_CORNECT_CONCAT(OCLING_CORNECT_CONCAT(head,SEP),OCLING_CORNECT_JOIN_WITH11(SEP,__VA_ARGS__))
#define OCLING_CORNECT_JOIN_WITH13(SEP,head,...) OCLING_CORNECT_CONCAT(OCLING_CORNECT_CONCAT(head,SEP),OCLING_CORNECT_JOIN_WITH12(SEP,__VA_ARGS__))
#define OCLING_CORNECT_JOIN_WITH14(SEP,head,...) OCLING_CORNECT_CONCAT(OCLING_CORNECT_CONCAT(head,SEP),OCLING_CORNECT_JOIN_WITH13(SEP,__VA_ARGS__))
#define OCLING_CORNECT_JOIN_WITH15(SEP,head,...) OCLING_CORNECT_CONCAT(OCLING_CORNECT_CONCAT(head,SEP),OCLING_CORNECT_JOIN_WITH14(SEP,__VA_ARGS__))
#define OCLING_CORNECT_JOIN_WITH16(SEP,head,...) OCLING_CORNECT_CONCAT(OCLING_CORNECT_CONCAT(head,SEP),OCLING_CORNECT_JOIN_WITH15(SEP,__VA_ARGS__))
#define OCLING_CORNECT_JOIN_WITH17(SEP,head,...) OCLING_CORNECT_CONCAT(OCLING_CORNECT_CONCAT(head,SEP),OCLING_CORNECT_JOIN_WITH16(SEP,__VA_ARGS__))
#define OCLING_CORNECT_JOIN_WITH18(SEP,head,...) OCLING_CORNECT_CONCAT(OCLING_CORNECT_CONCAT(head,SEP),OCLING_CORNECT_JOIN_WITH17(SEP,__VA_ARGS__))
#define OCLING_CORNECT_JOIN_WITH19(SEP,head,...) OCLING_CORNECT_CONCAT(OCLING_CORNECT_CONCAT(head,SEP),OCLING_CORNECT_JOIN_WITH18(SEP,__VA_ARGS__))
#define OCLING_CORNECT_JOIN_WITH20(SEP,head,...) OCLING_CORNECT_CONCAT(OCLING_CORNECT_CONCAT(head,SEP),OCLING_CORNECT_JOIN_WITH19(SEP,__VA_ARGS__))

#endif /* OCLingCoreConnect_h */
